{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "chatapp.fullname" . }}-aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.serviceAccountName }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "chatapp.fullname" . }}-backend-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "chatapp.fullname" . }}-aws-secretsmanager
    kind: SecretStore
  target:
    name: {{ include "chatapp.fullname" . }}-backend-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: {{ .Values.externalSecrets.remoteSecretKey }}
        property: MONGODB_URI
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.externalSecrets.remoteSecretKey }}
        property: JWT_SECRET
    - secretKey: CLIENT_URL
      remoteRef:
        key: {{ .Values.externalSecrets.remoteSecretKey }}
        property: CLIENT_URL
    - secretKey: CLOUDINARY_URL
      remoteRef:
        key: {{ .Values.externalSecrets.remoteSecretKey }}
        property: CLOUDINARY_URL
{{- end }}
