apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-external-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: backend-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: /production/chatapp/backend
        property: MONGODB_URI
    - secretKey: JWT_SECRET
      remoteRef:
        key: /production/chatapp/backend
        property: JWT_SECRET
    - secretKey: CLIENT_URL
      remoteRef:
        key: /production/chatapp/backend
        property: CLIENT_URL
    - secretKey: CLOUDINARY_URL
      remoteRef:
        key: /production/chatapp/backend
        property: CLOUDINARY_URL
